export const gradeRemarks = {
  "A+": "Exceptional",
  "A": "Impressive",
  "B+": "Promising",
  "B": "Steady",
  "C+": "Emerging",
  "C": "Developing",
  "S": "Basic",
};

export const students = [
  {
    name: "JIGNSHUV MEENA",
    mother: "REKHA MEENA",
    father: "DINESH CHANDRA MEENA",
    dob: "8/20/2011",
    scholarNo: "1",
    rollNo: "11",
    class: "NURSERY",
    unitTest: [
      { subject: "ENGLISH", marks: [28, 15, 25, 49, 56, 173] },
      { subject: "HINDI", marks: [27, 24, 18, 44, 57, 170] },
      { subject: "MATHS", marks: [27, 25, 21, 42, 25, 140] },
    ],
    totalMarks: 200,
    marksObtained: 150,
    percentage: "85.5",
    division: "First",
    attendance: "329",
    result: "Pass",
    activities: [
      ["Drawing", "A"],
      ["Physical Ed.", "A"],
    ],
    remark: "",
    promotion: "",
    resultDate: "",
    grade: "A",
  },
  {
    name: "TANVI MEGHWAL",
    mother: "SONU MEGHWAL",
    father: "SURESH MEGHWAL",
    dob: "12/2/2011",
    scholarNo: "2",
    rollNo: "2",
    class: "I",
    unitTest: [
      { subject: "ENGLISH", marks: [25, 27, 45, 55, 18, 170] },
      { subject: "HINDI", marks: [26, 28, 45, 55, 16, 140] },
      { subject: "MATHS", marks: [27, 24, 45, 55, 16, 130] },
    ],
    totalMarks: 200,
    marksObtained: 170,
    percentage: "85",
    division: "First",
    attendance: "85",
    result: "Pass",
    activities: [
      ["Drawing", "A"],
      ["Physical Ed.", "A"],
    ],
    remark: "",
    promotion: "",
    resultDate: "",
  },
  {
    name: "MANISH TELI",
    mother: "DHANVAR KUMARI",
    father: "DURGA SUWAKA TELI",
    dob: "7/11/2011",
    scholarNo: "3",
    rollNo: "3",
    class: "I",
    unitTest: [
      { subject: "ENGLISH", marks: [28, 28, 46, 50, 18, 170] },
      { subject: "HINDI", marks: [25, 26, 46, 50, 18, 160] },
      { subject: "MATHS", marks: [26, 26, 46, 50, 15, 150] },
    ],
    totalMarks: 200,
    marksObtained: 160,
    percentage: "80",
    division: "First",
    attendance: "80",
    result: "Pass",
    activities: [
      ["Drawing", "A"],
      ["Physical Ed.", "A"],
    ],
    remark: "",
    promotion: "",
    resultDate: "",
  },
  {
    name: "VICOM DAS MAHAJAT",
    mother: "SUDHIRDHA MAHAJAT",
    father: "NANDESHWAR DAS",
    dob: "1/14/2012",
    scholarNo: "4",
    rollNo: "4",
    class: "I",
    unitTest: [
      { subject: "ENGLISH", marks: [21, 27, 15, 66, 20, 129] },
      { subject: "HINDI", marks: [22, 25, 15, 66, 20, 128] },
      { subject: "MATHS", marks: [20, 20, 15, 66, 15, 125] },
    ],
    totalMarks: 200,
    marksObtained: 172,
    percentage: "61.5",
    division: "Second",
    attendance: "61.5",
    result: "Pass",
    activities: [
      ["Drawing", "A"],
      ["Physical Ed.", "A"],
    ],
    remark: "",
    promotion: "",
    resultDate: "",
  },
  {
    name: "SURAJPAL SINGH SISODIYA",
    mother: "SHIL SISODIYA",
    father: "BALWANT SINGH SISODIYA",
    dob: "6/25/2011",
    scholarNo: "5",
    rollNo: "5",
    class: "I",
    unitTest: [
      { subject: "ENGLISH", marks: [21, 27, 15, 66, 20, 129] },
      { subject: "HINDI", marks: [22, 25, 15, 66, 20, 128] },
      { subject: "MATHS", marks: [25, 25, 15, 66, 15, 129] },
    ],
    totalMarks: 200,
    marksObtained: 168,
    percentage: "61.5",
    division: "Second",
    attendance: "61.5",
    result: "Pass",
    activities: [
      ["Drawing", "A"],
      ["Physical Ed.", "A"],
    ],
    remark: "",
    promotion: "",
    resultDate: "",
  },
];
